FROM python:3.11-alpine3.17 as fast
WORKDIR /

COPY ./fastapi/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./fastapi  ./

EXPOSE 800

CMD ["uvicorn", "main:app", "--forwarded-allow-ips='*'", "--host", "0.0.0.0",  "--port", "800"]